services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    env_file:
      - PKFAuditManagement/.env
    ports:
      - "1433:1433"
    volumes:
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
      - sqlserver-data:/var/opt/mssql
    entrypoint: /usr/local/bin/entrypoint.sh
    networks:
      - app-network

  auditapp:
    build:
      context: . # Path to the directory with the Dockerfile
    container_name: auditapp
    env_file:
      - PKFAuditManagement/.env
    ports:
      - "5000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data:
